from django.utils.translation import gettext_lazy as _

CENTRAL_MANAGER_EDUCATION_GROUP = 'CENTRAL_MANAGER_EDUCATION_GROUP'
FACTULTY_MANAGER_EDUCATION_GROUP = 'FACTULTY_MANAGER_EDUCATION_GROUP'
CONTINUING_EDUCATION_TRAINING_MANAGER = 'CONTINUING_EDUCATION_TRAINING_MANAGER'
CONTINUING_EDUCATION_STUDENT_WORKER = 'CONTINUING_EDUCATION_STUDENT_WORKER'
CONTINUING_EDUCATION_MANAGER = 'CONTINUING_EDUCATION_MANAGER'
PARTNERSHIP_ENTITY_MANAGER = 'PARTNERSHIP_ENTITY_MANAGER'
PARTNERSHIP_VIEWER = 'PARTNERSHIP_VIEWER'
PARCOURS_VIEWER = 'PARCOURS_VIEWER'
TUTOR = 'TUTOR'
PROGRAM_MANAGER = 'PROGRAM_MANAGER'
ENTITY_MANAGER = 'ENTITY_MANAGER'
CATALOG_VIEWER = 'CATALOG_VIEWER'
JURY_SECRETARY = 'JURY_SECRETARY'
SIC_DIRECTOR = 'SIC_DIRECTOR'
SIC_MANAGER = 'SIC_MANAGER'
SCEB = 'SCEB'
PROMOTER = 'PROMOTER'
DOCTORATE_READER = 'DOCTORATE_READER'
CDD_MANAGER = 'CDD_MANAGER'
COMMITTEE_MEMBER = 'COMMITTEE_MEMBER'
ADRE_SECRETARY = 'ADRE_SECRETARY'
CANDIDATE = 'CANDIDATE'
CENTRAL_ADMISSION_MANAGER_EDUCATION_GROUP = 'CENTRAL_ADMISSION_MANAGER_EDUCATION_GROUP'
CENTRAL_MANAGER_LEARNING_UNIT = 'CENTRAL_MANAGER_LEARNING_UNIT'
FACULTY_MANAGER_LEARNING_UNIT = 'FACULTY_MANAGER_LEARNING_UNIT'

ROLES_OSIS_CHOICES = (
    (CENTRAL_MANAGER_EDUCATION_GROUP, _('Central Manager Education Group')),
    (FACTULTY_MANAGER_EDUCATION_GROUP, _('Faculty Manager Education Group')),
    (CONTINUING_EDUCATION_TRAINING_MANAGER, _('Continuing Education Training Manager')),
    (CONTINUING_EDUCATION_STUDENT_WORKER, _('Continuing Education Student Worker')),
    (CONTINUING_EDUCATION_MANAGER, _('Continuing Education Manager')),
    (PARTNERSHIP_ENTITY_MANAGER, _('Partnership Entity Manager')),
    (PARTNERSHIP_VIEWER, _('Partnership Viewer')),
    (PARCOURS_VIEWER, _('Parcours Viewer')),
    (TUTOR, _('Tutor')),
    (PROGRAM_MANAGER, _('Program Manager')),
    (ENTITY_MANAGER, _('Entity Manager')),
    (CATALOG_VIEWER, _('Catalog Viewer')),
    (JURY_SECRETARY, _('Jury Secretary')),
    (SIC_DIRECTOR, _('Sic Director')),
    (SIC_MANAGER, _('Sic Manager')),
    (SCEB, _('Sceb')),
    (PROMOTER, _('Promoter')),
    (DOCTORATE_READER, _('Doctorate Reader')),
    (CDD_MANAGER, _('Cdd Manager')),
    (COMMITTEE_MEMBER, _('Committee Member')),
    (ADRE_SECRETARY, _('Adre Secretary')),
    (CANDIDATE, _('Candidate')),
    (CENTRAL_ADMISSION_MANAGER_EDUCATION_GROUP, _('Central Admission Manager Education Group')),
    (CENTRAL_MANAGER_LEARNING_UNIT, _('Central Manager Learning Unit')),
    (FACULTY_MANAGER_LEARNING_UNIT, _('Faculty Manager Learning Unit')),
)
