from django.utils.translation import gettext_lazy as _

CENTRAL_MANAGER_EDUCATION_GROUP = 'CENTRAL_MANAGER_EDUCATION_GROUP'
FACTULTY_MANAGER_EDUCATION_GROUP = 'FACTULTY_MANAGER_EDUCATION_GROUP'
CONTINUING_EDUCATION_TRAINING_MANAGER = 'CONTINUING_EDUCATION_TRAINING_MANAGER'
CONTINUING_EDUCATION_STUDENT_WORKER = 'CONTINUING_EDUCATION_STUDENT_WORKER'
CONTINUING_EDUCATION_MANAGER = 'CONTINUING_EDUCATION_MANAGER'
PARTNERSHIP_ENTITY_MANAGER = 'PARTNERSHIP_ENTITY_MANAGER'
PARTNERSHIP_VIEWER = 'PARTNERSHIP_VIEWER'
PARCOURS_VIEWER = 'PARCOURS_VIEWER'
TUTOR = 'TUTOR'
PROGRAM_MANAGER = 'PROGRAM_MANAGER'
ENTITY_MANAGER = 'ENTITY_MANAGER'
CATALOG_VIEWER = 'CATALOG_VIEWER'
JURY_SECRETARY = 'JURY_SECRETARY'
SIC_DIRECTOR = 'SIC_DIRECTOR'
SIC_MANAGER = 'SIC_MANAGER'
SCEB = 'SCEB'
PROMOTER = 'PROMOTER'
DOCTORATE_READER = 'DOCTORATE_READER'
CDD_MANAGER = 'CDD_MANAGER'
COMMITTEE_MEMBER = 'COMMITTEE_MEMBER'
ADRE_SECRETARY = 'ADRE_SECRETARY'
CANDIDATE = 'CANDIDATE'
CENTRAL_ADMISSION_MANAGER_EDUCATION_GROUP = 'CENTRAL_ADMISSION_MANAGER_EDUCATION_GROUP'
CENTRAL_MANAGER_LEARNING_UNIT = 'CENTRAL_MANAGER_LEARNING_UNIT'
FACULTY_MANAGER_LEARNING_UNIT = 'FACULTY_MANAGER_LEARNING_UNIT'

ROLES_OSIS_CHOICES = (
    (CENTRAL_MANAGER_EDUCATION_GROUP, _("Gestionnaire central d'organisateur de formations")),
    (FACTULTY_MANAGER_EDUCATION_GROUP, _("Gestionnaire Facultaire d'organisateur de formations")),
    (CONTINUING_EDUCATION_TRAINING_MANAGER, _('Gestionnaire de formation continue')),
    (CONTINUING_EDUCATION_STUDENT_WORKER, _('Jobiste IUFC')),
    (CONTINUING_EDUCATION_MANAGER, _('Gestionnaire central IUFC')),
    (PARTNERSHIP_ENTITY_MANAGER, _('Gestionnaire de partenariats')),
    (PARTNERSHIP_VIEWER, _('Observateur de partenariat')),
    (PARCOURS_VIEWER, _('Consultation du parcours étudiant')),
    (TUTOR, _('Tuteur')),
    (PROGRAM_MANAGER, _('Gestionnaire de parcours étudiant')),
    (ENTITY_MANAGER, _("Gestionnaire d'entités")),
    (CATALOG_VIEWER, _('Lecteur du catalogue')),
    (JURY_SECRETARY, _('Secrétaire de jury')),
    (SIC_DIRECTOR, _('Directeur SIC')),
    (SIC_MANAGER, _('Gestionnaire SIC')),
    (SCEB, _('Sceb')),
    (PROMOTER, _('Promoteur')),
    (DOCTORATE_READER, _('Lecteur doctorat')),
    (CDD_MANAGER, _('Gestionnaire CDD')),
    (COMMITTEE_MEMBER, _('Membre du comité')),
    (ADRE_SECRETARY, _('Secrétaire ADRE')),
    (CANDIDATE, _('Candidat')),
    (CENTRAL_ADMISSION_MANAGER_EDUCATION_GROUP, _("Gestionnaire central d'admission d'organisateur de formations")),
    (CENTRAL_MANAGER_LEARNING_UNIT, _('Gestionnaire central (UE)')),
    (FACULTY_MANAGER_LEARNING_UNIT, _('Gestionnaire Facultaire (UE)')),
)
