# Generated by Django 3.2.16 on 2022-10-26 13:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=50)),
                ('formateur_id', models.CharField(max_length=50)),
                ('formation_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation_metier.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(max_length=50)),
                ('register_date', models.DateTimeField(default=datetime.datetime(2022, 10, 26, 13, 17, 17, 751547))),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation_metier.session')),
            ],
        ),
    ]
