# Generated by Django 3.2.16 on 2022-12-09 16:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import formation_metier.models.seance
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeUCLouvain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('matricule_fgs', models.CharField(max_length=8)),
                ('role_formation_metier', models.CharField(choices=[('PARTICIPANT', 'Participant'), ('FORMATEUR', 'Formateur'), ('ADMIN', 'Administrateur')], default='PARTICIPANT', max_length=200)),
            ],
            options={
                'permissions': [('access_to_formation_fare', 'Global access to module formation FARE'), ('suppression_inscription_par_participant', 'Can delete self inscription')],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[A-Za-z]{1,4}[0-9]{1,2}$')])),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('public_cible', models.CharField(choices=[('CENTRAL_MANAGER_EDUCATION_GROUP', 'Central Manager Education Group'), ('FACTULTY_MANAGER_EDUCATION_GROUP', 'Faculty Manager Education Group'), ('CONTINUING_EDUCATION_TRAINING_MANAGER', 'Continuing Education Training Manager'), ('CONTINUING_EDUCATION_STUDENT_WORKER', 'Continuing Education Student Worker'), ('CONTINUING_EDUCATION_MANAGER', 'Continuing Education Manager'), ('PARTNERSHIP_ENTITY_MANAGER', 'Partnership Entity Manager'), ('PARTNERSHIP_VIEWER', 'Partnership Viewer'), ('PARCOURS_VIEWER', 'Parcours Viewer'), ('TUTOR', 'Tutor'), ('PROGRAM_MANAGER', 'Program Manager'), ('ENTITY_MANAGER', 'Entity Manager'), ('CATALOG_VIEWER', 'Catalog Viewer'), ('JURY_SECRETARY', 'Jury Secretary'), ('SIC_DIRECTOR', 'Sic Director'), ('SIC_MANAGER', 'Sic Manager'), ('SCEB', 'Sceb'), ('PROMOTER', 'Promoter'), ('DOCTORATE_READER', 'Doctorate Reader'), ('CDD_MANAGER', 'Cdd Manager'), ('COMMITTEE_MEMBER', 'Committee Member'), ('ADRE_SECRETARY', 'Adre Secretary'), ('CANDIDATE', 'Candidate'), ('CENTRAL_ADMISSION_MANAGER_EDUCATION_GROUP', 'Central Admission Manager Education Group'), ('CENTRAL_MANAGER_LEARNING_UNIT', 'Central Manager Learning Unit'), ('FACULTY_MANAGER_LEARNING_UNIT', 'Faculty Manager Learning Unit')], default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seance_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('local', models.CharField(max_length=50)),
                ('participant_max_number', models.PositiveSmallIntegerField(default=20)),
                ('duree', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(600)])),
                ('formateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formation_metier.employeuclouvain', validators=[formation_metier.models.seance.validate_formateur])),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation_metier.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inscription_date', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation_metier.employeuclouvain')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation_metier.seance')),
            ],
        ),
        migrations.AddConstraint(
            model_name='formation',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_formation_code'),
        ),
        migrations.AddField(
            model_name='employeuclouvain',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='seance',
            constraint=models.UniqueConstraint(fields=('seance_date', 'local', 'formateur'), name='unique_session'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('seance', 'participant')},
        ),
        migrations.AddConstraint(
            model_name='employeuclouvain',
            constraint=models.UniqueConstraint(fields=('matricule_fgs',), name='unique_person'),
        ),
    ]
