# Generated by Django 3.2.16 on 2023-02-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seance',
            name='unique_session',
        ),
        migrations.AlterField(
            model_name='formation',
            name='public_cible',
            field=models.CharField(choices=[('CENTRAL_MANAGER_EDUCATION_GROUP', "Gestionnaire central d'organisateur de formations"), ('FACTULTY_MANAGER_EDUCATION_GROUP', "Gestionnaire Facultaire d'organisateur de formations"), ('CONTINUING_EDUCATION_TRAINING_MANAGER', 'Gestionnaire de formation continue'), ('CONTINUING_EDUCATION_STUDENT_WORKER', 'Jobiste IUFC'), ('CONTINUING_EDUCATION_MANAGER', 'Gestionnaire central IUFC'), ('PARTNERSHIP_ENTITY_MANAGER', 'Gestionnaire de partenariats'), ('PARTNERSHIP_VIEWER', 'Observateur de partenariat'), ('PARCOURS_VIEWER', 'Consultation du parcours étudiant'), ('TUTOR', 'Tuteur'), ('PROGRAM_MANAGER', 'Gestionnaire de parcours étudiant'), ('ENTITY_MANAGER', "Gestionnaire d'entités"), ('CATALOG_VIEWER', 'Lecteur du catalogue'), ('JURY_SECRETARY', 'Secrétaire de jury'), ('SIC_DIRECTOR', 'Directeur SIC'), ('SIC_MANAGER', 'Gestionnaire SIC'), ('SCEB', 'Sceb'), ('PROMOTER', 'Promoteur'), ('DOCTORATE_READER', 'Lecteur doctorat'), ('CDD_MANAGER', 'Gestionnaire CDD'), ('COMMITTEE_MEMBER', 'Membre du comité'), ('ADRE_SECRETARY', 'Secrétaire ADRE'), ('CANDIDATE', 'Candidat'), ('CENTRAL_ADMISSION_MANAGER_EDUCATION_GROUP', "Gestionnaire central d'admission d'organisateur de formations"), ('CENTRAL_MANAGER_LEARNING_UNIT', 'Gestionnaire central (UE)'), ('FACULTY_MANAGER_LEARNING_UNIT', 'Gestionnaire Facultaire (UE)')], default=None, max_length=200),
        ),
        migrations.RemoveField(
            model_name='seance',
            name='formateur',
        ),
        migrations.AddField(
            model_name='seance',
            name='formateur',
            field=models.ManyToManyField(to='formation_metier.EmployeUCLouvain'),
        ),
        migrations.AddConstraint(
            model_name='seance',
            constraint=models.UniqueConstraint(fields=('seance_date', 'local'), name='unique_session'),
        ),
    ]
