# Generated by Django 3.2.16 on 2023-02-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0002_auto_20230227_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='formateur',
            field=models.ManyToManyField(limit_choices_to={'role_formation_metier': 'FORMATEUR'}, to='formation_metier.EmployeUCLouvain'),
        ),
    ]
