# Generated by Django 3.2.16 on 2022-10-26 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0002_alter_register_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 13, 46, 41, 260682, tzinfo=utc)),
        ),
    ]
