# Generated by Django 3.2.16 on 2023-02-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0003_alter_seance_formateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeuclouvain',
            name='email',
            field=models.EmailField(default='default.email@uclouvain.be', max_length=255),
        ),
    ]
