# Generated by Django 3.2.16 on 2022-10-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0003_alter_register_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='register_date',
            field=models.DateTimeField(),
        ),
    ]
