# Generated by Django 3.2.16 on 2022-12-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0003_alter_employeuclouvain_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeuclouvain',
            options={'permissions': [('access_to_formation_fare', 'Global access to module formation FARE'), ('delete_self_register', 'Can delete self register')]},
        ),
    ]
