# Generated by Django 3.2.16 on 2022-10-26 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0004_alter_register_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='participant_max_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='session_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
