# Generated by Django 3.2.16 on 2023-02-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0004_employeuclouvain_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='seance_date',
            field=models.DateTimeField(),
        ),
    ]
