# Generated by Django 3.2.16 on 2022-10-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0005_auto_20221026_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
