# Generated by Django 3.2.16 on 2022-10-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0006_alter_register_register_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='formation_code',
            new_name='formation',
        ),
    ]
