# Generated by Django 3.2.16 on 2022-11-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0007_rename_formation_code_session_formation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('numberFGS', models.CharField(max_length=8)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('formateur', 'formateur'), ('participant', 'participant')], max_length=20)),
            ],
        ),
    ]
