# Generated by Django 3.2.16 on 2022-12-08 10:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0007_alter_employeuclouvain_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inscription_date', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation_metier.employeuclouvain')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation_metier.seance')),
            ],
            options={
                'unique_together': {('seance', 'participant')},
            },
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
