# Generated by Django 3.2.16 on 2022-11-02 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0008_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation_metier.person'),
        ),
    ]
