# Generated by Django 3.2.16 on 2022-12-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0008_auto_20221208_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeuclouvain',
            options={'permissions': [('access_to_formation_fare', 'Global access to module formation FARE'), ('suppression_inscription_par_participant', 'Can delete self inscription')]},
        ),
    ]
