# Generated by Django 3.2.16 on 2022-11-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0009_alter_register_participant'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='register',
            constraint=models.UniqueConstraint(fields=('session', 'participant'), name='unique_register'),
        ),
    ]
