# Generated by Django 3.2.16 on 2022-12-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0010_auto_20221209_1541'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeuclouvain',
            name='unique_person',
        ),
        migrations.RenameField(
            model_name='employeuclouvain',
            old_name='number_fgs',
            new_name='matricule_fgs',
        ),
        migrations.AddConstraint(
            model_name='employeuclouvain',
            constraint=models.UniqueConstraint(fields=('matricule_fgs',), name='unique_person'),
        ),
    ]
