# Generated by Django 3.2.16 on 2022-11-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0010_register_unique_register'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='formation',
            constraint=models.UniqueConstraint(fields=('code', 'name'), name='unique_formation_code_name'),
        ),
    ]
