# Generated by Django 3.2.16 on 2022-11-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0011_formation_unique_formation_code_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='formation',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_formation_code'),
        ),
    ]
