# Generated by Django 3.2.16 on 2022-11-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0012_formation_unique_formation_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='formation',
            name='unique_formation_code_name',
        ),
    ]
