# Generated by Django 3.2.16 on 2022-11-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0014_session_public_cible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='public_cible',
            field=models.CharField(choices=[('Admin', 'Administrateurs'), ('Form', 'Formateurs'), ('Part', 'Participant')], default='Part', max_length=50),
        ),
    ]
