# Generated by Django 3.2.16 on 2022-11-10 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0015_alter_session_public_cible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RoleOsis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
        migrations.AddField(
            model_name='person',
            name='role_formation_metier',
            field=models.CharField(choices=[('Admin', 'Administrateurs'), ('Form', 'Formateurs'), ('Part', 'Participant')], default='Part', max_length=20),
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formation_metier.formateur')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formation_metier.participant')),
                ('role_osis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation_metier.roleosis')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation_metier.person'),
        ),
        migrations.AddField(
            model_name='formateur',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation_metier.person'),
        ),
        migrations.AddConstraint(
            model_name='personrole',
            constraint=models.CheckConstraint(check=models.Q(('participant__isnull', False), ('formateur__isnull', False), _connector='OR'), name='constraint_formateur_or_participant'),
        ),
    ]
