# Generated by Django 3.2.16 on 2022-11-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0016_auto_20221110_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleosis',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
