# Generated by Django 3.2.16 on 2022-11-16 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0017_alter_roleosis_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[A-Z]{1-4}[1-9]{1-2}$')]),
        ),
        migrations.DeleteModel(
            name='PersonRole',
        ),
        migrations.DeleteModel(
            name='RoleOsis',
        ),
    ]
