# Generated by Django 3.2.16 on 2022-11-16 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0018_auto_20221116_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[A-Z]{1-4}[0-9]{1-2}$')]),
        ),
    ]
