# Generated by Django 3.2.16 on 2022-11-16 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0019_alter_formation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[A-Za-z]{1,4}[0-9]{1,2}$')]),
        ),
    ]
