# Generated by Django 3.2.16 on 2022-11-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0020_alter_formation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role_formation_metier',
            field=models.CharField(blank=True, choices=[('CENTRAL_MANAGER_EDUCATION_GROUP', 'Central Manager Education Group'), ('FACTULTY_MANAGER_EDUCATION_GROUP', 'Faculty Manager Education Group'), ('CONTINUING_EDUCATION_TRAINING_MANAGER', 'Continuing Education Training Manager'), ('CONTINUING_EDUCATION_STUDENT_WORKER', 'Continuing Education Student Worker'), ('CONTINUING_EDUCATION_MANAGER', 'Continuing Education Manager'), ('PARTNERSHIP_ENTITY_MANAGER', 'Partnership Entity Manager'), ('PARTNERSHIP_VIEWER', 'Partnership Viewer'), ('PARCOURS_VIEWER', 'Parcours Viewer'), ('TUTOR', 'Tutor'), ('PROGRAM_MANAGER', 'Program Manager'), ('ENTITY_MANAGER', 'Entity Manager'), ('CATALOG_VIEWER', 'Catalog Viewer'), ('JURY_SECRETARY', 'Jury Secretary'), ('SIC_DIRECTOR', 'Sic Director'), ('SIC_MANAGER', 'Sic Manager'), ('SCEB', 'Sceb'), ('PROMOTER', 'Promoter'), ('DOCTORATE_READER', 'Doctorate Reader'), ('CDD_MANAGER', 'Cdd Manager'), ('COMMITTEE_MEMBER', 'Committee Member'), ('ADRE_SECRETARY', 'Adre Secretary'), ('CANDIDATE', 'Candidate'), ('CENTRAL_ADMISSION_MANAGER_EDUCATION_GROUP', 'Central Admission Manager Education Group'), ('CENTRAL_MANAGER_LEARNING_UNIT', 'Central Manager Learning Unit'), ('FACULTY_MANAGER_LEARNING_UNIT', 'Faculty Manager Learning Unit')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='public_cible',
            field=models.CharField(choices=[('CENTRAL_MANAGER_EDUCATION_GROUP', 'Central Manager Education Group'), ('FACTULTY_MANAGER_EDUCATION_GROUP', 'Faculty Manager Education Group'), ('CONTINUING_EDUCATION_TRAINING_MANAGER', 'Continuing Education Training Manager'), ('CONTINUING_EDUCATION_STUDENT_WORKER', 'Continuing Education Student Worker'), ('CONTINUING_EDUCATION_MANAGER', 'Continuing Education Manager'), ('PARTNERSHIP_ENTITY_MANAGER', 'Partnership Entity Manager'), ('PARTNERSHIP_VIEWER', 'Partnership Viewer'), ('PARCOURS_VIEWER', 'Parcours Viewer'), ('TUTOR', 'Tutor'), ('PROGRAM_MANAGER', 'Program Manager'), ('ENTITY_MANAGER', 'Entity Manager'), ('CATALOG_VIEWER', 'Catalog Viewer'), ('JURY_SECRETARY', 'Jury Secretary'), ('SIC_DIRECTOR', 'Sic Director'), ('SIC_MANAGER', 'Sic Manager'), ('SCEB', 'Sceb'), ('PROMOTER', 'Promoter'), ('DOCTORATE_READER', 'Doctorate Reader'), ('CDD_MANAGER', 'Cdd Manager'), ('COMMITTEE_MEMBER', 'Committee Member'), ('ADRE_SECRETARY', 'Adre Secretary'), ('CANDIDATE', 'Candidate'), ('CENTRAL_ADMISSION_MANAGER_EDUCATION_GROUP', 'Central Admission Manager Education Group'), ('CENTRAL_MANAGER_LEARNING_UNIT', 'Central Manager Learning Unit'), ('FACULTY_MANAGER_LEARNING_UNIT', 'Faculty Manager Learning Unit')], default=None, max_length=50),
        ),
    ]
