# Generated by Django 3.2.16 on 2022-11-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0021_auto_20221117_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role_formation_metier',
            field=models.CharField(blank=True, choices=[('PARTICIPANT', 'Participant'), ('FORMATEUR', 'Formateur'), ('ADMIN', 'Administrateur')], default=None, max_length=50),
        ),
    ]
