# Generated by Django 3.2.16 on 2022-11-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0022_alter_person_role_formation_metier'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('numberFGS',), name='unique_person'),
        ),
    ]
