# Generated by Django 3.2.16 on 2022-11-21 12:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0023_person_unique_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='duree',
            field=models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AlterField(
            model_name='session',
            name='formateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formation_metier.formateur'),
        ),
    ]
