# Generated by Django 3.2.16 on 2022-11-21 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0024_auto_20221121_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='formateur',
            new_name='formateur_id',
        ),
    ]
