# Generated by Django 3.2.16 on 2022-11-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0025_rename_formateur_session_formateur_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='formateur_id',
            new_name='formateur',
        ),
    ]
