# Generated by Django 3.2.16 on 2022-11-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0026_rename_formateur_id_session_formateur'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('session_date', 'local', 'formateur'), name='unique_session'),
        ),
    ]
