# Generated by Django 3.2.16 on 2022-11-22 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0027_session_unique_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation_metier.participant'),
        ),
    ]
