# Generated by Django 3.2.16 on 2022-11-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0031_alter_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role_formation_metier',
            field=models.CharField(choices=[('PARTICIPANT', 'Participant'), ('FORMATEUR', 'Formateur'), ('ADMIN', 'Administrateur')], default='PARTICIPANT', max_length=50),
        ),
    ]
