# Generated by Django 3.2.16 on 2022-11-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0034_auto_20221125_1344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='Seance',
        ),
        migrations.RemoveConstraint(
            model_name='register',
            name='unique_register',
        ),
        migrations.RemoveConstraint(
            model_name='seance',
            name='unique_session',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='session',
            new_name='seance',
        ),
        migrations.RenameField(
            model_name='seance',
            old_name='session_date',
            new_name='seance_date',
        ),
        migrations.AddConstraint(
            model_name='register',
            constraint=models.UniqueConstraint(fields=('seance', 'participant'), name='unique_register'),
        ),
        migrations.AddConstraint(
            model_name='seance',
            constraint=models.UniqueConstraint(fields=('seance_date', 'local', 'formateur'), name='unique_session'),
        ),
    ]
