# Generated by Django 3.2.16 on 2022-11-28 11:40

from django.db import migrations, models
import django.db.models.deletion
import formation_metier.models.seance


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0036_auto_20221128_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='formateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formation_metier.employeuclouvain', validators=[formation_metier.models.seance.validate_formateur]),
        ),
    ]
