# Generated by Django 3.2.16 on 2022-11-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0037_alter_seance_formateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='participant_max_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
