# Generated by Django 3.2.16 on 2022-11-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0038_alter_seance_participant_max_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeuclouvain',
            name='unique_person',
        ),
        migrations.RenameField(
            model_name='employeuclouvain',
            old_name='numberFGS',
            new_name='number_fgs',
        ),
        migrations.AddConstraint(
            model_name='employeuclouvain',
            constraint=models.UniqueConstraint(fields=('number_fgs',), name='unique_person'),
        ),
    ]
