# Generated by Django 3.2.16 on 2022-11-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation_metier', '0039_auto_20221129_1212'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='register',
            name='unique_register',
        ),
        migrations.AlterUniqueTogether(
            name='register',
            unique_together={('seance', 'participant')},
        ),
    ]
